### ISSUE TITLE
Error while processing

### ISSUE THREAD

**Issue by octoma** [tradytics/surpriver#20]
Hello, I keep getting the following error while the script is running.

`Exception __init__() got an unexpected keyword argument 'n'`

Then, when finished, it gives this error:

`Exception in thread Thread-2123:
Traceback (most recent call last):
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/site-packages/yfinance/multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/site-packages/yfinance/multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/sage/anaconda3/envs/Cerebus/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I'm running it on Anaconda and all of the requirements are installed.
I've also tried this, in case it was a Python version issue.

`python3 detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 1 --future_bars 25`

Ialso found these in the detection_engine.py

# Basic libraries
import os
import ta = Not working
import sys = Not working
import json
import math = Not working
import pickle = Not working
import random = Not working
import requests = Not working
import collections
import numpy as np
from os import walk = Not working, path
import pandas as pd = Not working
import yfinance as yf = Not working
import datetime as dt
from scipy.stats import linregress = Not working
from datetime import datetime = Not working, timedelta = Not working
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from data_loader import DataEngine
import warnings

**Comment by james-vervitas** [comment]
Have you found a solution to the problem yet, I am having the same issue? 
I did have to comment out the code that runs the Binance module as I was having problems with that.

**Comment by adobayua-rpay** [comment]
Anyone found a solution to this yet?

**Comment by xeonvs** [comment]
Solution https://pastebin.com/VeVTfJQ1
