### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by guijames** [tradytics/surpriver#21]
After running the below:

python detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 0 --future_bars 0

Here is the error message:

Traceback (most recent call last):
  File "detection_engine.py", line 357, in <module>
    supriver.find_anomalies()
  File "detection_engine.py", line 196, in find_anomalies
    features, historical_price_info, future_prices, symbol_names = self.dataEngine.collect_data_for_all_tickers()
  File "/Users/Home/Documents/Coding/surpriver-master/data_loader.py", line 211, in collect_data_for_all_tickers
    features, historical_price_info, future_price_info, symbol_names = self.remove_bad_data(features, historical_price_info, future_price_info, symbol_names)
  File "/Users/Home/Documents/Coding/surpriver-master/data_loader.py", line 249, in remove_bad_data
    most_common_length = length_dictionary[0]
IndexError: list index out of range

**Comment by xeonvs** [comment]
Use this patch
https://pastebin.com/VeVTfJQ1

**Comment by guijames** [comment]
Thank you! Very much appreciated.
