### ISSUE TITLE
How do I fix my JSON error when it doesn't show loading data for all stocks?

### ISSUE THREAD

**Issue by MasterHiddenTank** [tradytics/surpriver#24]
Hey everyone,

I've been using surpriver for a little while and this was the first time that this has happened. Thanks!

```Checking arguments...
Surpriver has been initialized...
Data engine has been initialized...
Loading all stocks from file...
Total number of stocks: 5693
Technical Indicator Engine has been initialized
Loading data for all stocks...
  0%|                                                  | 0/5693 [00:00<?, ?it/s]Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/usr/local/lib/python3.8/dist-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/usr/local/lib/python3.8/dist-packages/yfinance/base.py", line 155, in history
    data = data.json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Stas1407** [comment]
I've faced the same issue and updating yfinance to 0.1.63 worked for me.

**Comment by MasterHiddenTank** [comment]
> I've faced the same issue and updating yfinance to 0.1.63 worked for me.

Cool! I'll try it later!

**Comment by MasterHiddenTank** [comment]
> I've faced the same issue and updating yfinance to 0.1.63 worked for me.

Works thanks!
