### ISSUE TITLE
ImportError: No module named ta

### ISSUE THREAD

**Issue by stockpsyop** [tradytics/surpriver#9]
Using python3

Installed using: 
$ pip3 install -r requirements.txt

Ran code:
$ python detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 1 --future_bars 25
Traceback (most recent call last):
  File "detection_engine.py", line 3, in <module>
    import ta
ImportError: No module named ta

**Comment by shaggy63** [comment]
pip install -r requirements.txt

No need to run detection_engine or pip with sudo.

**Comment by stockpsyop** [comment]
Error still remains even without "sudo":

spector@spector-K53Z**:**~/Downloads/surpriver-master$ pip3 install -r requirements.txt****
Requirement already satisfied: certifi==2020.6.20 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: cycler==0.10.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: idna==2.10 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: joblib==0.16.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.16.0)
Requirement already satisfied: kiwisolver==1.2.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.2.0)
Requirement already satisfied: matplotlib==3.3.1 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (3.3.1)
Requirement already satisfied: multitasking==0.0.9 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (0.0.9)
Requirement already satisfied: numpy==1.19.1 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (1.19.1)
Requirement already satisfied: pandas==1.1.1 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.1.1)
Requirement already satisfied: Pillow==7.2.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (7.2.0)
Requirement already satisfied: pyparsing==2.4.7 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (2.4.7)
Requirement already satisfied: python-dateutil==2.8.1 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2.8.1)
Requirement already satisfied: pytz==2020.1 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (2020.1)
Requirement already satisfied: requests==2.24.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (2.24.0)
Requirement already satisfied: scikit-learn==0.23.2 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (0.23.2)
Requirement already satisfied: scipy==1.5.2 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (1.5.2)
Requirement already satisfied: six==1.15.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (1.15.0)
Requirement already satisfied: ta==0.5.25 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (0.5.25)
Requirement already satisfied: threadpoolctl==2.1.0 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (2.1.0)
Requirement already satisfied: tqdm==4.48.2 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (4.48.2)
Requirement already satisfied: urllib3==1.25.10 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (1.25.10)
Requirement already satisfied: yfinance==0.1.54 in /home/spector/.local/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (0.1.54)
spector@spector-K53Z**:~/Downloads/surpriver-master$ python detection_engine.py** --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 1 --future_bars 25

Traceback (most recent call last):
  File "detection_engine.py", line 3, in <module>
    import ta
ImportError: No module named ta

Is there a configuration setting I am missing?

**Comment by shaggy63** [comment]
If you have to run pip3 then you may have python 2.7 (default) and python3 installed. Run it with python3 instead of just python.

python3 detection_engine.py --top_n 25 --min_volume 5000 --data_granularity_minutes 60 --history_to_use 14 --is_load_from_dictionary 0 --data_dictionary_path 'dictionaries/data_dict.npy' --is_save_dictionary 1 --is_test 1 --future_bars 25
